### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by jrs1002** [jrs1002/GESPRO_GESTIONTAREAS#26]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by jrs1002** [comment]
#### Anexos

- [ ] Plan de proyecto software
- [ ] Especificación de requisitos
- [ ] Especificación de diseño
- [ ] Manual del programador
- [ ] Manual de usuario

Expresión regular para corregir referencias;

- Buscar: `(\{\[\})([\w:\\]+)(\{\]\}\\\_)`
- Reemplazar por: `\\citep{\2}`

Expresión regular para corregir las imágenes 
- Buscar: `(\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})`
- Reemplazar por: `\\imagen{\2}{descripción...}`

Ej: `\includegraphics{../../img/s2.png}` -> `\imagen{s2}{descripción...}}`

**Comment by psf1002** [comment]
Document Manual Programador #151

**Comment by psf1002** [comment]
Convert annex C to latex #151
