### ISSUE TITLE
Pasar anexos a Latex

### ISSUE THREAD

**Issue by jrs1002** [jrs1002/GESPRO_GESTIONTAREAS#28]
#### Anexos

- [x] Plan de proyecto software
- [x] Especificación de requisitos
- [x] Especificación de diseño
- [x] Manual del programador
- [x] Manual de usuario
----
Expresión regular para corregir referencias;

- Buscar: `(\{\[\})([\w:\\]+)(\{\]\}\\\_)`
- Reemplazar por: `\\citep{\2}`
----
Expresión regular para corregir las imágenes 
- Buscar: `(\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})`
- Reemplazar por: `\\imagen{\2}{descripción...}`

Ej: `\includegraphics{../../img/s2.png}` -> `\imagen{s2}{descripción...}}`

**Comment by psf1002** [comment]
Convert annex D to latex #179

**Comment by psf1002** [comment]
Convert annex E to latex #179

**Comment by psf1002** [comment]
Convert annex B to latex #179

**Comment by psf1002** [comment]
Convert annex A to latex #179
