### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by jrs1002** [jrs1002/GESPRO_GESTIONTAREAS#5]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by jrs1002** [comment]
davidmigloz added a commit that referenced this issue on 11 Feb 2017

**Comment by mmv1001** [comment]
http://gobees.io/
